"""First migration

Revision ID: 7145f2629494
Revises: 
Create Date: 2023-05-06 17:39:54.852268

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7145f2629494"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "banner",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_banner_id"), "banner", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(
        op.f("ix_user_full_name"), "user", ["full_name"], unique=False
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "experiment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_description"),
        "experiment",
        ["description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiment_id"), "experiment", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_experiment_name"), "experiment", ["name"], unique=False
    )
    op.create_table(
        "design",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("zip_file_name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("condensed", sa.Boolean(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_design_id"), "design", ["id"], unique=False)
    op.create_index(
        op.f("ix_design_name"), "design", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_design_zip_file_name"),
        "design",
        ["zip_file_name"],
        unique=False,
    )
    op.create_table(
        "resultzip",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resultzip_id"), "resultzip", ["id"], unique=False
    )
    op.create_table(
        "construct",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("genbank", sa.String(), nullable=True),
        sa.Column("j5_construct_id", sa.Integer(), nullable=True),
        sa.Column("assembly_method", sa.String(), nullable=True),
        sa.Column("jbx", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("design_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["design_id"],
            ["design.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_construct_id"), "construct", ["id"], unique=False
    )
    op.create_table(
        "oligo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("j5_oligo_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("length", sa.Integer(), nullable=True),
        sa.Column("tm", sa.Float(), nullable=True),
        sa.Column("tm_3p", sa.Float(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("sequence", sa.String(), nullable=True),
        sa.Column("sequence_3p", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("design_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["design_id"],
            ["design.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_oligo_id"), "oligo", ["id"], unique=False)
    op.create_index(
        op.f("ix_oligo_j5_oligo_id"),
        "oligo",
        ["j5_oligo_id"],
        unique=False,
    )
    op.create_index(op.f("ix_oligo_name"), "oligo", ["name"], unique=False)
    op.create_table(
        "part",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("j5_part_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("part_type", sa.String(), nullable=True),
        sa.Column("type_id", sa.Integer(), nullable=True),
        sa.Column("relative_overlap", sa.Integer(), nullable=True),
        sa.Column("extra_5p_bps", sa.Integer(), nullable=True),
        sa.Column("extra_3p_bps", sa.Integer(), nullable=True),
        sa.Column("overlap_with_next", sa.String(), nullable=True),
        sa.Column("overlap_with_next_rc", sa.String(), nullable=True),
        sa.Column("sequence_length", sa.Integer(), nullable=True),
        sa.Column("sequence", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("design_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["design_id"],
            ["design.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_part_id"), "part", ["id"], unique=False)
    op.create_index(
        op.f("ix_part_j5_part_id"), "part", ["j5_part_id"], unique=False
    )
    op.create_index(op.f("ix_part_name"), "part", ["name"], unique=False)
    op.create_table(
        "rawdesign",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("design_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["design_id"],
            ["design.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rawdesign_id"), "rawdesign", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_rawdesign_name"), "rawdesign", ["name"], unique=False
    )
    op.create_table(
        "synth",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("j5_synth_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("length", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("sequence", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("design_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["design_id"],
            ["design.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_synth_id"), "synth", ["id"], unique=False)
    op.create_index(
        op.f("ix_synth_j5_synth_id"),
        "synth",
        ["j5_synth_id"],
        unique=False,
    )
    op.create_index(op.f("ix_synth_name"), "synth", ["name"], unique=False)
    op.create_table(
        "workflow",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_time", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("design_id", sa.Integer(), nullable=True),
        sa.Column("resultzip_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["design_id"],
            ["design.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resultzip_id"],
            ["resultzip.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_created_time"),
        "workflow",
        ["created_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_id"), "workflow", ["id"], unique=False
    )
    op.create_table(
        "assembly",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("j5_assembly_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("assembly_method", sa.String(), nullable=True),
        sa.Column("bin", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("design_id", sa.Integer(), nullable=True),
        sa.Column("construct_id", sa.Integer(), nullable=True),
        sa.Column("part_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["construct_id"],
            ["construct.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["design_id"],
            ["design.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["part.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assembly_id"), "assembly", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_assembly_j5_assembly_id"),
        "assembly",
        ["j5_assembly_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assembly_name"), "assembly", ["name"], unique=False
    )
    op.create_table(
        "digest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("j5_digest_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("length", sa.Integer(), nullable=True),
        sa.Column("sequence", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("part_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["part.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_digest_id"), "digest", ["id"], unique=False)
    op.create_index(
        op.f("ix_digest_j5_digest_id"),
        "digest",
        ["j5_digest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_digest_source"), "digest", ["source"], unique=False
    )
    op.create_table(
        "instruction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("trial", sa.Integer(), nullable=True),
        sa.Column("data", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("workflow_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_instruction_id"), "instruction", ["id"], unique=False
    )
    op.create_table(
        "plate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("raw_data", sa.String(), nullable=True),
        sa.Column("plate_type", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("workflow_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plate_id"), "plate", ["id"], unique=False)
    op.create_table(
        "template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("j5_template_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("design_id", sa.Integer(), nullable=True),
        sa.Column("synth_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["design_id"],
            ["design.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["synth_id"],
            ["synth.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_template_id"), "template", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_template_j5_template_id"),
        "template",
        ["j5_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_name"), "template", ["name"], unique=False
    )
    op.create_table(
        "workflowstep",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("workflow_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflowstep_id"), "workflowstep", ["id"], unique=False
    )
    op.create_table(
        "pcr",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("j5_pcr_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("mean_oligo_temp", sa.Float(), nullable=True),
        sa.Column("delta_oligo_temp", sa.Float(), nullable=True),
        sa.Column("mean_oligo_temp_3p", sa.Float(), nullable=True),
        sa.Column("delta_oligo_temp_3p", sa.Float(), nullable=True),
        sa.Column("length", sa.Integer(), nullable=True),
        sa.Column("sequence", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("part_id", sa.Integer(), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("forward_oligo_id", sa.Integer(), nullable=True),
        sa.Column("reverse_oligo_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["forward_oligo_id"],
            ["oligo.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["part.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reverse_oligo_id"],
            ["oligo.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["template.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pcr_id"), "pcr", ["id"], unique=False)
    op.create_index(
        op.f("ix_pcr_j5_pcr_id"), "pcr", ["j5_pcr_id"], unique=False
    )
    op.create_table(
        "plate_to_instruction",
        sa.Column("plate_id", sa.Integer(), nullable=True),
        sa.Column("instruction_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instruction_id"],
            ["instruction.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plate_id"],
            ["plate.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("instrument", sa.String(), nullable=True),
        sa.Column("raw_data", sa.String(), nullable=True),
        sa.Column("run_type", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("instruction_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instruction_id"],
            ["instruction.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_id"), "run", ["id"], unique=False)
    op.create_table(
        "well",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("well_type", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("plate_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plate_id"],
            ["plate.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_well_id"), "well", ["id"], unique=False)
    op.create_table(
        "digestwell",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["digest.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["well.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_digestwell_id"), "digestwell", ["id"], unique=False
    )
    op.create_table(
        "oligoorder96well",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["oligo.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["well.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oligoorder96well_id"),
        "oligoorder96well",
        ["id"],
        unique=False,
    )
    op.create_table(
        "oligowell",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["oligo.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["well.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oligowell_id"), "oligowell", ["id"], unique=False
    )
    op.create_table(
        "partwell",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["part.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["well.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_partwell_id"), "partwell", ["id"], unique=False
    )
    op.create_table(
        "pcr_to_oligo",
        sa.Column("pcr_id", sa.Integer(), nullable=True),
        sa.Column("oligo_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["oligo_id"],
            ["oligo.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pcr_id"], ["pcr.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
    )
    op.create_table(
        "pcrwell",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["pcr.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["well.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pcrwell_id"), "pcrwell", ["id"], unique=False)
    op.create_table(
        "result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("result_type", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["run.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_result_id"), "result", ["id"], unique=False)
    op.create_table(
        "synthwell",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["synth.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["well.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_synthwell_id"), "synthwell", ["id"], unique=False
    )
    op.create_table(
        "templatewell",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["template.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["well.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_templatewell_id"), "templatewell", ["id"], unique=False
    )
    op.create_table(
        "assemblyresult",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("colonies", sa.Boolean(), nullable=True),
        sa.Column("sample_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["result.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["construct.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assemblyresult_id"),
        "assemblyresult",
        ["id"],
        unique=False,
    )
    op.create_table(
        "pcrresult",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("polymerase", sa.String(), nullable=True),
        sa.Column("good", sa.Boolean(), nullable=True),
        sa.Column("sample_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["result.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["pcrwell.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pcrresult_id"), "pcrresult", ["id"], unique=False
    )
    op.create_table(
        "sequencingresult",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sequencing", sa.Boolean(), nullable=True),
        sa.Column("sample_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["result.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["construct.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sequencingresult_id"),
        "sequencingresult",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sequencingresult_id"), table_name="sequencingresult"
    )
    op.drop_table("sequencingresult")
    op.drop_index(op.f("ix_pcrresult_id"), table_name="pcrresult")
    op.drop_table("pcrresult")
    op.drop_index(
        op.f("ix_assemblyresult_id"), table_name="assemblyresult"
    )
    op.drop_table("assemblyresult")
    op.drop_index(op.f("ix_templatewell_id"), table_name="templatewell")
    op.drop_table("templatewell")
    op.drop_index(op.f("ix_synthwell_id"), table_name="synthwell")
    op.drop_table("synthwell")
    op.drop_index(op.f("ix_result_id"), table_name="result")
    op.drop_table("result")
    op.drop_index(op.f("ix_pcrwell_id"), table_name="pcrwell")
    op.drop_table("pcrwell")
    op.drop_table("pcr_to_oligo")
    op.drop_index(op.f("ix_partwell_id"), table_name="partwell")
    op.drop_table("partwell")
    op.drop_index(op.f("ix_oligowell_id"), table_name="oligowell")
    op.drop_table("oligowell")
    op.drop_index(
        op.f("ix_oligoorder96well_id"), table_name="oligoorder96well"
    )
    op.drop_table("oligoorder96well")
    op.drop_index(op.f("ix_digestwell_id"), table_name="digestwell")
    op.drop_table("digestwell")
    op.drop_index(op.f("ix_well_id"), table_name="well")
    op.drop_table("well")
    op.drop_index(op.f("ix_run_id"), table_name="run")
    op.drop_table("run")
    op.drop_table("plate_to_instruction")
    op.drop_index(op.f("ix_pcr_j5_pcr_id"), table_name="pcr")
    op.drop_index(op.f("ix_pcr_id"), table_name="pcr")
    op.drop_table("pcr")
    op.drop_index(op.f("ix_workflowstep_id"), table_name="workflowstep")
    op.drop_table("workflowstep")
    op.drop_index(op.f("ix_template_name"), table_name="template")
    op.drop_index(
        op.f("ix_template_j5_template_id"), table_name="template"
    )
    op.drop_index(op.f("ix_template_id"), table_name="template")
    op.drop_table("template")
    op.drop_index(op.f("ix_plate_id"), table_name="plate")
    op.drop_table("plate")
    op.drop_index(op.f("ix_instruction_id"), table_name="instruction")
    op.drop_table("instruction")
    op.drop_index(op.f("ix_digest_source"), table_name="digest")
    op.drop_index(op.f("ix_digest_j5_digest_id"), table_name="digest")
    op.drop_index(op.f("ix_digest_id"), table_name="digest")
    op.drop_table("digest")
    op.drop_index(op.f("ix_assembly_name"), table_name="assembly")
    op.drop_index(
        op.f("ix_assembly_j5_assembly_id"), table_name="assembly"
    )
    op.drop_index(op.f("ix_assembly_id"), table_name="assembly")
    op.drop_table("assembly")
    op.drop_index(op.f("ix_workflow_id"), table_name="workflow")
    op.drop_index(op.f("ix_workflow_created_time"), table_name="workflow")
    op.drop_table("workflow")
    op.drop_index(op.f("ix_synth_name"), table_name="synth")
    op.drop_index(op.f("ix_synth_j5_synth_id"), table_name="synth")
    op.drop_index(op.f("ix_synth_id"), table_name="synth")
    op.drop_table("synth")
    op.drop_index(op.f("ix_rawdesign_name"), table_name="rawdesign")
    op.drop_index(op.f("ix_rawdesign_id"), table_name="rawdesign")
    op.drop_table("rawdesign")
    op.drop_index(op.f("ix_part_name"), table_name="part")
    op.drop_index(op.f("ix_part_j5_part_id"), table_name="part")
    op.drop_index(op.f("ix_part_id"), table_name="part")
    op.drop_table("part")
    op.drop_index(op.f("ix_oligo_name"), table_name="oligo")
    op.drop_index(op.f("ix_oligo_j5_oligo_id"), table_name="oligo")
    op.drop_index(op.f("ix_oligo_id"), table_name="oligo")
    op.drop_table("oligo")
    op.drop_index(op.f("ix_construct_id"), table_name="construct")
    op.drop_table("construct")
    op.drop_index(op.f("ix_resultzip_id"), table_name="resultzip")
    op.drop_table("resultzip")
    op.drop_index(op.f("ix_design_zip_file_name"), table_name="design")
    op.drop_index(op.f("ix_design_name"), table_name="design")
    op.drop_index(op.f("ix_design_id"), table_name="design")
    op.drop_table("design")
    op.drop_index(op.f("ix_experiment_name"), table_name="experiment")
    op.drop_index(op.f("ix_experiment_id"), table_name="experiment")
    op.drop_index(
        op.f("ix_experiment_description"), table_name="experiment"
    )
    op.drop_table("experiment")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_full_name"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_banner_id"), table_name="banner")
    op.drop_table("banner")
    # ### end Alembic commands ###
